# Site settings
title: Awesome Site to Demo Jekyll
github_username: cdworkshops
description: >
  This is a practice site to demo Jekyll.
 
url: "https://cdworkshops.github.io/cats"

# Build settings
markdown: kramdown
theme: minima
